version: "3.9"
services:
    postgres:
        image:  postgres:15
        environment:
            POSTGRES_DB: "efdb"
            POSTGRES_USER: "ef"
            POSTGRES_PASSWORD: "ef"
        ports:
            - "5432:5432"
        networks:
            - postgres

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:7.2
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "5050:80"
        networks:
            - postgres

networks:
    postgres:
        driver: bridge
